exp_name_complt: PCN_16384
batch_size: 16
workers: 0
epochs_complt: 100
model_name: pcn
load_model: null
#load_model: log/pcn_cd_debug_2023-01-11T17:51:55/best_cd_p_network.pth
#load_model: log/pcn_cd_debug_2023-03-22T14:50:17/network.pth
start_epoch: 0
num_points: 2048
work_dir: log/
flag: debug
loss: cd
manual_seed: null
use_mean_feature: False
step_interval_to_print: 100
epoch_interval_to_save: 1
epoch_interval_to_val: 1
varying_constant: 0.01, 0.1, 0.5, 1
varying_constant_epochs: 5, 15, 30

lr_complt: 0.0001
lr_decay: True
lr_decay_interval: 40
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

#dcp
exp_name_reg: idam
model: dcp
eval: True
num_iter: 3
emb_nn: GNN
pointer: transformer
head: svd
emb_dims: 64
n_blocks: 1
n_heads: 4
ff_dims: 1024
dropout: 0.0
epochs_reg: 100
use_sgd: False
lr_reg: 0.0001
momentum: 0.9
no_cuda: False
seed: 1234
cycle: False
gaussian_noise: False
unseen: False
dataset: MVP
factor: 4
model_path: null
alpha: 0.75

# test
save_vis: False
#save_vis: True